In [1]:
import numpy as np

In [2]:
a = np.fromfunction(lambda x, y: 10 * x + y, (2, 2))

In [3]:
a

array([[ 0.,  1.],
       [10., 11.]])

In [4]:
b = np.array([[21, 22], 
              [23, 24]], dtype=np.float64)

In [5]:
b

array([[21., 22.],
       [23., 24.]])

In [6]:
np.hstack((a, b))

array([[ 0.,  1., 21., 22.],
       [10., 11., 23., 24.]])

In [7]:
np.vstack((a, b))

array([[ 0.,  1.],
       [10., 11.],
       [21., 22.],
       [23., 24.]])

In [8]:
np.r_[1:10, 101, 102]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 101, 102])

In [9]:
np.r_[101, 102, 1:10]

array([101, 102,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [11]:
np.c_[0:10, 100:110]

array([[  0, 100],
       [  1, 101],
       [  2, 102],
       [  3, 103],
       [  4, 104],
       [  5, 105],
       [  6, 106],
       [  7, 107],
       [  8, 108],
       [  9, 109]])

In [14]:
c = np.c_[np.array([[1, 2, 3]]), 0, 0, np.array([[10, 11, 12]])]

In [15]:
c.shape

(1, 8)

In [16]:
c

array([[ 1,  2,  3,  0,  0, 10, 11, 12]])

In [17]:
c.size

8