In [1]:
import numpy as np

In [2]:
a = np.fromfunction(lambda x, y: 10 * x + y, (3, 4))

In [3]:
a

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.]])

In [4]:
a.shape

(3, 4)

In [5]:
a.ravel()

array([ 0.,  1.,  2.,  3., 10., 11., 12., 13., 20., 21., 22., 23.])

In [7]:
b = a.reshape(6, 2)

In [8]:
b

array([[ 0.,  1.],
       [ 2.,  3.],
       [10., 11.],
       [12., 13.],
       [20., 21.],
       [22., 23.]])

In [9]:
b.shape

(6, 2)

In [10]:
a.T

array([[ 0., 10., 20.],
       [ 1., 11., 21.],
       [ 2., 12., 22.],
       [ 3., 13., 23.]])

In [23]:
c = a.reshape(4, -1) # -1 calculate other dimension automatically

In [14]:
c

array([[ 0.,  1.,  2.],
       [ 3., 10., 11.],
       [12., 13., 20.],
       [21., 22., 23.]])

In [15]:
a.resize(6, 2)

In [16]:
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [10., 11.],
       [12., 13.],
       [20., 21.],
       [22., 23.]])

In [17]:
a.shape

(6, 2)

In [24]:
a.resize(3, 4) # inline array dimension changes

In [19]:
a.shape

(3, 4)

In [20]:
a

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.]])

In [21]:
np.hsplit(a, 2)

[array([[ 0.,  1.],
        [10., 11.],
        [20., 21.]]),
 array([[ 2.,  3.],
        [12., 13.],
        [22., 23.]])]

In [22]:
np.vsplit(a, 3)

[array([[0., 1., 2., 3.]]),
 array([[10., 11., 12., 13.]]),
 array([[20., 21., 22., 23.]])]