In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([10, 11, 12])

In [5]:
b

array([10, 11, 12])

In [6]:
a + b

array([11, 13, 15])

In [7]:
a - b

array([-9, -9, -9])

In [8]:
a * b

array([10, 22, 36])

In [9]:
a / b

array([0.1       , 0.18181818, 0.25      ])

In [10]:
b > 10

array([False,  True,  True])

In [11]:
a ** 2

array([1, 4, 9])

In [12]:
a.min()

np.int64(1)

In [13]:
b.max()

np.int64(12)

In [14]:
a.cumsum()

array([1, 3, 6])

In [15]:
a.sum()

np.int64(6)

In [16]:
c = np.array([
    [2, 4, 6], 
    [3, 5, 7]
])

In [17]:
d = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

In [18]:
c

array([[2, 4, 6],
       [3, 5, 7]])

In [19]:
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
c @ d

array([[44, 56],
       [53, 68]])

In [21]:
c.dot(d)

array([[44, 56],
       [53, 68]])

In [22]:
c.sum(axis=0)

array([ 5,  9, 13])

In [23]:
c.sum(axis=1)

array([12, 15])

In [25]:
np.sqrt(c)

array([[1.41421356, 2.        , 2.44948974],
       [1.73205081, 2.23606798, 2.64575131]])

In [26]:
np.exp(c)

array([[   7.3890561 ,   54.59815003,  403.42879349],
       [  20.08553692,  148.4131591 , 1096.63315843]])