In [1]:
import numpy as np

In [2]:
a = np.arange(10) ** 3

In [3]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
a[1:6]

array([  1,   8,  27,  64, 125])

In [5]:
a[1:]

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [6]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [7]:
for i in a:
    print(i * np.pi)

0.0
3.141592653589793
25.132741228718345
84.82300164692441
201.06192982974676
392.6990816987241
678.5840131753953
1077.5662801812991
1608.495438637974
2290.221044466959


In [8]:
def array_function(x, y):
    return 10 * x + y
    

In [11]:
b = np.fromfunction(array_function, (5, 4), dtype=np.int64)

In [12]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [13]:
b[1,]

array([10, 11, 12, 13])

In [15]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [16]:
b[3,2]

np.int64(32)

In [17]:
b[1,0:3]

array([10, 11, 12])

In [18]:
b[0:3,1]

array([ 1, 11, 21])

In [22]:
b[1, ...] # b[1, :]

array([10, 11, 12, 13])

In [21]:
b[..., 3] # b[:, 3]

array([ 3, 13, 23, 33, 43])

In [30]:
c = np.fromfunction(lambda i, x, y: 10 * x + y + i, (2, 2, 3), dtype=np.int64)

In [31]:
c

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [11, 12, 13]]])

In [32]:
c[0, 0, 2]

np.int64(2)

In [33]:
c[0, ...] # c[0, :, :]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [34]:
c[0, :, :]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [35]:
c[1, ...]

array([[ 1,  2,  3],
       [11, 12, 13]])

In [36]:
c[1, :, 1]

array([ 2, 12])

In [44]:
c[..., 2] # c[:, :, 2]

array([[ 2, 12],
       [ 3, 13]])

In [38]:
c[:, :, 2]

array([[ 2, 12],
       [ 3, 13]])

In [39]:
for i in b:
    print(i)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [40]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [42]:
for m in c:
    for i in m:
        print(i)

[0 1 2]
[10 11 12]
[1 2 3]
[11 12 13]


In [43]:
for m in c:
    for element in m.flat:
        print(element)

0
1
2
10
11
12
1
2
3
11
12
13
