In [1]:
import numpy as np

In [2]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b = a

In [5]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b is a

True

In [7]:
c = a.view()

In [8]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
c is a

False

In [10]:
id(c)

1741784544144

In [11]:
id(a)

1741784544432

In [12]:
c.flags.owndata

False

In [14]:
c[0, 3] = 1234

In [15]:
c

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [16]:
a

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [17]:
c.base is a

True

In [18]:
c = c.reshape((2, 6))

In [19]:
c

array([[   0,    1,    2, 1234,    4,    5],
       [   6,    7,    8,    9,   10,   11]])

In [20]:
a

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [36]:
s = a[:, 1:3] #Returns a view of it

In [22]:
s.base is a

True

In [23]:
s.flags.owndata

False

In [24]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [25]:
s[:] = 10

In [26]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [27]:
a

array([[   0,   10,   10, 1234],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])

In [35]:
d = a.copy() # Deep copy: The copy method makes a complete copy of the array and its data.

In [29]:
d.base is a

False

In [30]:
d.flags.owndata

True

In [31]:
d

array([[   0,   10,   10, 1234],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])

In [32]:
d[0, 0] = 100

In [33]:
d

array([[ 100,   10,   10, 1234],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])

In [34]:
a

array([[   0,   10,   10, 1234],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])